apiVersion: backstage.io/v1alpha1
kind: Resource
metadata:
  name: spring-28jan-qay-gitops
  description: This is GitOps manifest for spring-28jan-qay   
  links:
    - url: https://www.redhat.com/en/solutions/trusted-software-supply-chain
      title: Trusted Secure Supply Chain 
      icon: dashboard
      type: admin-dashboard
  annotations:    
    argocd/app-name: spring-28jan-qay
    backstage.io/kubernetes-id: spring-28jan-qay 
    backstage.io/techdocs-ref: dir:. 
    janus-idp.io/tekton: spring-28jan-qay   
spec:
  type: gitops
  owner: user:guest 
  lifecycle: experimental
  dependsOn:
    - component:spring-28jan-qay
